"""
NLP Sentiment Classifier — Production-Quality ML Pipeline
==========================================================
Author : [Your Name]
Dataset : IMDb Movie Reviews (50,000 reviews, binary sentiment)
Models  : Multinomial Naive Bayes | Logistic Regression | Linear SVM
Task    : Binary Text Classification (Positive / Negative)

Usage:
  python classifier.py --train              # Train and evaluate all models
  python classifier.py --text "I loved it"  # Predict sentiment for custom text
  python classifier.py --train --text "..."  # Both
"""

import os
import sys
import time
import argparse
import warnings
import pickle
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")          # headless backend — safe for all environments
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_files
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    accuracy_score, f1_score, classification_report, confusion_matrix
)
from sklearn.utils import shuffle

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────────────────────
# Constants
# ─────────────────────────────────────────────────────────────────────────────

RANDOM_STATE  = 42
TEST_SIZE     = 0.20       # 80 / 20 train-test split
MAX_FEATURES  = 50_000     # TF-IDF vocabulary cap
MODELS_DIR    = "models"
PLOTS_DIR     = "plots"
DATA_CSV      = "data/imdb_sample.csv"   # generated by generate_data.py

LABEL_MAP = {0: "Negative 😞", 1: "Positive 😊"}

# ─────────────────────────────────────────────────────────────────────────────
# Utilities
# ─────────────────────────────────────────────────────────────────────────────

def banner(text: str) -> None:
    """Print a formatted section banner."""
    width = 70
    print("\n" + "═" * width)
    print(f"  {text}")
    print("═" * width)


def ensure_dirs(*dirs: str) -> None:
    """Create directories if they don't already exist."""
    for d in dirs:
        os.makedirs(d, exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
# Data Loading & Preprocessing
# ─────────────────────────────────────────────────────────────────────────────

def load_data(csv_path: str = DATA_CSV):
    """
    Load the IMDb sentiment dataset from a CSV file.

    Returns
    -------
    X : list[str]   Raw review texts
    y : np.ndarray  Binary labels (0 = negative, 1 = positive)
    """
    banner("1. Loading Dataset")

    if not os.path.exists(csv_path):
        print(f"  ✗ Dataset not found at '{csv_path}'.")
        print("  → Run  python generate_data.py  first, then retry.")
        sys.exit(1)

    df = pd.read_csv(csv_path)
    df = shuffle(df, random_state=RANDOM_STATE).reset_index(drop=True)

    print(f"  ✓ Loaded {len(df):,} reviews from '{csv_path}'")
    print(f"  ✓ Class distribution:\n{df['label'].value_counts().to_string()}")

    X = df["text"].tolist()
    y = df["label"].values
    return X, y


def preprocess_text(texts: list) -> list:
    """
    Light-touch text cleaning applied *before* TF-IDF vectorisation:

    - Strip leading/trailing whitespace
    - Collapse multiple spaces
    - Convert to lower-case

    Note: heavy cleaning (stopword removal, stemming) is intentionally
    deferred to TfidfVectorizer so the pipeline remains reproducible.
    """
    import re
    cleaned = []
    for t in texts:
        t = t.strip()
        t = re.sub(r"\s+", " ", t)
        t = t.lower()
        cleaned.append(t)
    return cleaned


# ─────────────────────────────────────────────────────────────────────────────
# Pipeline Construction
# ─────────────────────────────────────────────────────────────────────────────

def build_pipelines() -> dict:
    """
    Return a dictionary of named scikit-learn Pipelines.

    Each pipeline bundles:
      Step 1 — TfidfVectorizer  (text → numeric feature matrix)
      Step 2 — Classifier       (numeric features → label prediction)

    TF-IDF settings
    ---------------
    - ngram_range=(1, 2)  : unigrams + bigrams capture short phrases
    - max_features=50,000 : caps vocabulary for memory efficiency
    - sublinear_tf=True   : apply 1 + log(tf) scaling to reduce outlier impact
    - min_df=2            : ignore tokens appearing in < 2 documents
    - stop_words="english" : remove common English stopwords
    """
    shared_tfidf = dict(
        ngram_range=(1, 2),
        max_features=MAX_FEATURES,
        sublinear_tf=True,
        min_df=2,
        stop_words="english",
    )

    pipelines = {
        "Naive Bayes": Pipeline([
            ("tfidf", TfidfVectorizer(**shared_tfidf)),
            ("clf",   MultinomialNB(alpha=0.1)),
        ]),
        "Logistic Regression": Pipeline([
            ("tfidf", TfidfVectorizer(**shared_tfidf)),
            ("clf",   LogisticRegression(
                C=5.0, max_iter=1000, solver="lbfgs",
                random_state=RANDOM_STATE, n_jobs=-1
            )),
        ]),
        "Linear SVM": Pipeline([
            ("tfidf", TfidfVectorizer(**shared_tfidf)),
            ("clf",   LinearSVC(C=1.0, max_iter=2000, random_state=RANDOM_STATE)),
        ]),
    }
    return pipelines


# ─────────────────────────────────────────────────────────────────────────────
# Training & Evaluation
# ─────────────────────────────────────────────────────────────────────────────

def train_and_evaluate(pipelines: dict, X_train, X_test, y_train, y_test) -> dict:
    """
    Train every pipeline and collect evaluation metrics.

    Returns
    -------
    results : dict  {model_name: {accuracy, f1, report, confusion_matrix, pipeline}}
    """
    banner("3. Training & Evaluating Models")
    results = {}

    for name, pipe in pipelines.items():
        print(f"\n  ▶  {name}")
        t0 = time.time()

        # ── Train ────────────────────────────────────────────────────────────
        pipe.fit(X_train, y_train)
        train_time = time.time() - t0

        # ── Predict ──────────────────────────────────────────────────────────
        y_pred = pipe.predict(X_test)

        # ── Metrics ──────────────────────────────────────────────────────────
        acc  = accuracy_score(y_test, y_pred)
        f1   = f1_score(y_test, y_pred, average="weighted")
        cm   = confusion_matrix(y_test, y_pred)
        rep  = classification_report(y_test, y_pred,
                                     target_names=["Negative", "Positive"])

        print(f"     Accuracy  : {acc:.4f}  ({acc*100:.2f}%)")
        print(f"     F1-Score  : {f1:.4f}")
        print(f"     Train time: {train_time:.2f}s")
        print(f"\n{rep}")

        results[name] = {
            "accuracy": acc,
            "f1": f1,
            "report": rep,
            "confusion_matrix": cm,
            "pipeline": pipe,
            "train_time": train_time,
        }

    return results


def cross_validate(pipelines: dict, X_train, y_train, cv: int = 5) -> dict:
    """
    Run k-fold cross-validation on the training split for robust estimates.

    Returns
    -------
    cv_scores : dict  {model_name: mean_cv_accuracy}
    """
    banner("4. Cross-Validation (5-Fold)")
    cv_scores = {}
    for name, pipe in pipelines.items():
        scores = cross_val_score(pipe, X_train, y_train,
                                 cv=cv, scoring="accuracy", n_jobs=-1)
        cv_scores[name] = scores.mean()
        print(f"  {name:25s}  CV Accuracy: {scores.mean():.4f} ± {scores.std():.4f}")
    return cv_scores


# ─────────────────────────────────────────────────────────────────────────────
# Visualisations
# ─────────────────────────────────────────────────────────────────────────────

PALETTE = ["#4C72B0", "#DD8452", "#55A868"]   # accessible colour cycle

def plot_model_comparison(results: dict) -> None:
    """Bar chart comparing Accuracy and F1-Score across all models."""
    names     = list(results.keys())
    accuracies = [results[n]["accuracy"] for n in names]
    f1_scores  = [results[n]["f1"]       for n in names]

    x     = np.arange(len(names))
    width = 0.35

    fig, ax = plt.subplots(figsize=(9, 5))
    bars1 = ax.bar(x - width/2, accuracies, width, label="Accuracy",  color=PALETTE[0])
    bars2 = ax.bar(x + width/2, f1_scores,  width, label="F1-Score",  color=PALETTE[1])

    # Annotate bars
    for bar in bars1:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.003,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=9)
    for bar in bars2:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.003,
                f"{bar.get_height():.3f}", ha="center", va="bottom", fontsize=9)

    ax.set_xlabel("Model", fontsize=12)
    ax.set_ylabel("Score", fontsize=12)
    ax.set_title("Model Comparison — Accuracy & F1-Score", fontsize=14, fontweight="bold")
    ax.set_xticks(x)
    ax.set_xticklabels(names, fontsize=11)
    ax.set_ylim(0.80, 1.00)
    ax.legend(fontsize=11)
    ax.grid(axis="y", linestyle="--", alpha=0.5)
    fig.tight_layout()

    path = os.path.join(PLOTS_DIR, "model_comparison.png")
    plt.savefig(path, dpi=150)
    plt.close()
    print(f"  ✓ Saved → {path}")


def plot_confusion_matrices(results: dict) -> None:
    """Side-by-side heatmaps of confusion matrices for all models."""
    n     = len(results)
    fig, axes = plt.subplots(1, n, figsize=(6 * n, 5))
    if n == 1:
        axes = [axes]

    labels = ["Negative", "Positive"]
    for ax, (name, data) in zip(axes, results.items()):
        cm = data["confusion_matrix"]
        sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                    xticklabels=labels, yticklabels=labels, ax=ax,
                    linewidths=0.5, linecolor="white",
                    annot_kws={"size": 13, "weight": "bold"})
        ax.set_title(name, fontsize=13, fontweight="bold")
        ax.set_xlabel("Predicted Label", fontsize=11)
        ax.set_ylabel("True Label",      fontsize=11)

    fig.suptitle("Confusion Matrices — All Models", fontsize=15, fontweight="bold", y=1.02)
    fig.tight_layout()

    path = os.path.join(PLOTS_DIR, "confusion_matrices.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✓ Saved → {path}")


def plot_top_features(results: dict, n_features: int = 20) -> None:
    """
    Horizontal bar charts of the top TF-IDF features for
    Logistic Regression (coefficients are directly interpretable).
    """
    name = "Logistic Regression"
    if name not in results:
        return

    pipe       = results[name]["pipeline"]
    vectorizer = pipe.named_steps["tfidf"]
    clf        = pipe.named_steps["clf"]

    feature_names = np.array(vectorizer.get_feature_names_out())
    coefs         = clf.coef_[0]

    top_pos_idx = np.argsort(coefs)[-n_features:][::-1]
    top_neg_idx = np.argsort(coefs)[:n_features]

    fig, axes = plt.subplots(1, 2, figsize=(14, 7))

    for ax, idx, title, colour in [
        (axes[0], top_pos_idx, "Top Positive Features", "#2ecc71"),
        (axes[1], top_neg_idx, "Top Negative Features", "#e74c3c"),
    ]:
        ax.barh(feature_names[idx][::-1], coefs[idx][::-1], color=colour, alpha=0.85)
        ax.set_title(title, fontsize=13, fontweight="bold")
        ax.set_xlabel("Coefficient Weight", fontsize=11)
        ax.grid(axis="x", linestyle="--", alpha=0.5)

    fig.suptitle(f"Logistic Regression — Top {n_features} Features by Class",
                 fontsize=14, fontweight="bold")
    fig.tight_layout()

    path = os.path.join(PLOTS_DIR, "top_features.png")
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.close()
    print(f"  ✓ Saved → {path}")


def plot_training_time(results: dict) -> None:
    """Bar chart of training times per model."""
    names  = list(results.keys())
    times  = [results[n]["train_time"] for n in names]

    fig, ax = plt.subplots(figsize=(7, 4))
    bars = ax.bar(names, times, color=PALETTE, alpha=0.85)
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.02,
                f"{bar.get_height():.2f}s", ha="center", va="bottom", fontsize=10)
    ax.set_ylabel("Time (seconds)", fontsize=12)
    ax.set_title("Model Training Time Comparison", fontsize=13, fontweight="bold")
    ax.grid(axis="y", linestyle="--", alpha=0.5)
    fig.tight_layout()

    path = os.path.join(PLOTS_DIR, "training_time.png")
    plt.savefig(path, dpi=150)
    plt.close()
    print(f"  ✓ Saved → {path}")


# ─────────────────────────────────────────────────────────────────────────────
# Model Persistence
# ─────────────────────────────────────────────────────────────────────────────

def save_best_model(results: dict) -> str:
    """
    Serialise the highest-accuracy pipeline to disk with pickle.

    Returns
    -------
    best_name : str  Name of the winning model
    """
    best_name = max(results, key=lambda n: results[n]["accuracy"])
    best_pipe = results[best_name]["pipeline"]

    path = os.path.join(MODELS_DIR, "best_model.pkl")
    with open(path, "wb") as f:
        pickle.dump({"model_name": best_name, "pipeline": best_pipe}, f)

    print(f"\n  ✓ Best model ({best_name}) saved → {path}")
    return best_name


def load_best_model() -> tuple:
    """
    Load the serialised best model from disk.

    Returns
    -------
    (model_name, pipeline)
    """
    path = os.path.join(MODELS_DIR, "best_model.pkl")
    if not os.path.exists(path):
        return None, None
    with open(path, "rb") as f:
        obj = pickle.load(f)
    return obj["model_name"], obj["pipeline"]


# ─────────────────────────────────────────────────────────────────────────────
# CLI Prediction
# ─────────────────────────────────────────────────────────────────────────────

def predict_text(text: str) -> None:
    """
    Load the best saved model and predict the sentiment of *text*.
    Prints a human-readable result with confidence (where available).
    """
    model_name, pipe = load_best_model()
    if pipe is None:
        print("  ✗ No trained model found. Run:  python classifier.py --train")
        return

    prediction = pipe.predict([text])[0]
    label      = LABEL_MAP[prediction]

    # Probability estimates (not available for LinearSVC without calibration)
    try:
        proba    = pipe.predict_proba([text])[0]
        conf     = max(proba) * 100
        conf_str = f"  Confidence : {conf:.1f}%"
    except AttributeError:
        conf_str = "  Confidence : N/A (LinearSVC)"

    print("\n" + "─" * 50)
    print(f"  Model      : {model_name}")
    print(f"  Input text : {text[:80]}{'…' if len(text) > 80 else ''}")
    print(f"  Sentiment  : {label}")
    print(conf_str)
    print("─" * 50)


# ─────────────────────────────────────────────────────────────────────────────
# Full Training Pipeline
# ─────────────────────────────────────────────────────────────────────────────

def run_training_pipeline() -> None:
    """End-to-end: load data → preprocess → train → evaluate → visualise → save."""
    ensure_dirs(MODELS_DIR, PLOTS_DIR)

    # 1. Data
    X, y = load_data()

    # 2. Preprocessing
    banner("2. Preprocessing Text")
    X = preprocess_text(X)
    print(f"  ✓ Cleaned {len(X):,} documents")

    # 3. Split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=TEST_SIZE, random_state=RANDOM_STATE, stratify=y
    )
    print(f"  ✓ Train: {len(X_train):,}  |  Test: {len(X_test):,}")

    # 4. Build pipelines
    pipelines = build_pipelines()

    # 5. Train & evaluate
    results = train_and_evaluate(pipelines, X_train, X_test, y_train, y_test)

    # 6. Cross-validation
    cross_validate(pipelines, X_train, y_train)

    # 7. Visualisations
    banner("5. Generating Visualisations")
    plot_model_comparison(results)
    plot_confusion_matrices(results)
    plot_top_features(results)
    plot_training_time(results)

    # 8. Save best model
    banner("6. Saving Best Model")
    best = save_best_model(results)

    banner("✅ Pipeline Complete")
    print(f"  Best model : {best}  ({results[best]['accuracy']*100:.2f}% accuracy)")
    print(f"  Plots      : ./{PLOTS_DIR}/")
    print(f"  Model      : ./{MODELS_DIR}/best_model.pkl\n")


# ─────────────────────────────────────────────────────────────────────────────
# Entry Point
# ─────────────────────────────────────────────────────────────────────────────

def parse_args():
    parser = argparse.ArgumentParser(
        description="NLP Sentiment Classifier — IMDb Movie Reviews",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "--train", action="store_true",
        help="Train all models and generate evaluation plots.",
    )
    parser.add_argument(
        "--text", type=str, default=None,
        help='Predict sentiment for a custom string.\nExample: --text "This movie was amazing!"',
    )
    return parser.parse_args()


def main():
    args = parse_args()

    if not args.train and args.text is None:
        print(__doc__)
        print("Run with --help for usage details.")
        sys.exit(0)

    if args.train:
        run_training_pipeline()

    if args.text:
        banner("Predicting Sentiment")
        predict_text(args.text)


if __name__ == "__main__":
    main()
